- name: E/duplicate
  color: 'BFD4F2'
  description: 'Closed: Same as another'
  aliases: []

- name: E/external
  color: 'BFD4F2'
  description: 'Closed: External issue'
  aliases: []

- name: E/invalid
  color: 'BFD4F2'
  description: 'Closed: Not an issue'
  aliases: []

- name: E/no-action
  color: 'BFD4F2'
  description: 'Closed: Not actionable or inadequate information'
  aliases: []
  
- name: E/scope
  color: 'BFD4F2'
  description: 'Closed: Out of scope'
  aliases: []

- name: E/wontfix
  color: 'BFD4F2'
  description: 'Closed: Will not be worked on'
  aliases: []



- name: P/high
  color: 'B60205'
  description: 'Priority: High, for immediate attention'
  aliases: []

- name: P/low
  color: '006B75'
  description: 'Priority: Low, not time-sensitive'
  aliases: []

- name: P/medium
  color: '36210B'
  description: 'Priority: Medium, time-sensitive but not urgent'
  aliases: []



- name: S/accepted
  color: '006B75'
  description: 'Status: Accepted but not assigned'
  aliases: []

- name: S/blocked
  color: '97988B'
  description: 'Status: Blocked by another event'
  aliases: []

- name: S/finished
  color: '0E8A16'
  description: 'Status: Complete, awaiting release'
  aliases: [fixed]

- name: S/info-needed
  color: 'FBCA04'
  description: 'Status: Awaiting further information'
  aliases: []

- name: S/in-progress
  color: '0052CC'
  description: 'Status: Being worked on'
  aliases: []

- name: S/needs-triage
  color: '36210B'
  description: 'Status: Needs triage'
  aliases: []



- name: T/addition
  color: '006B75'
  description: 'Type: New feature'
  aliases: []

- name: T/bug
  color: 'D93F0B'
  description: 'Type: Bug'
  aliases: []

- name: T/compat
  color: '490839'
  description: 'Type: Compatibility'
  aliases: []

- name: T/enhancement
  color: '0052CC'
  description: 'Type: Enhancement or optimization'
  aliases: []

- name: T/fix
  color: '0E8A16'
  description: 'Type: Issue fix'
  aliases: []

- name: T/port
  color: '5319E7'
  description: 'Type: Upgrade or downgrade game version'
  aliases: []

- name: T/security
  color: 'B60205'
  description: 'Type: Security issue'
  aliases: []
  
- name: T/translation
  color: '8C02DA'
  description: 'Type: Translation'
  aliases: []
