- name: E/duplicate
  color: 'BFD4F2'
  description: 'Closed: Same as another'
  aliases: [ ]

- name: E/external
  color: 'BFD4F2'
  description: 'Closed: External issue'
  aliases: [ ]

- name: E/invalid
  color: 'BFD4F2'
  description: 'Closed: Not an issue'
  aliases: [ ]

- name: E/no-action
  color: 'BFD4F2'
  description: 'Closed: Not actionable or inadequate information'
  aliases: [ ]

- name: E/scope
  color: 'BFD4F2'
  description: 'Closed: Out of scope'
  aliases: [ ]

- name: E/stale
  color: 'BFD4F2'
  description: 'Closed: Stale'
  aliases: [ ]

- name: E/wontfix
  color: 'BFD4F2'
  description: 'Closed: Will not be worked on'
  aliases: [ ]


- name: P/critical
  color: 'B60205'
  description: 'Priority: Critical, requires immediate attention'
  aliases: [ ]

- name: P/high
  color: 'A83400'
  description: 'Priority: High'
  aliases: [ ]

- name: P/low
  color: '172B72'
  description: 'Priority: Low, not time-sensitive'
  aliases: [ ]

- name: P/medium
  color: '006B75'
  description: 'Priority: Medium'
  aliases: [ ]


- name: S/accepted
  color: '172B72'
  description: 'Status: Accepted or confirmed'
  aliases: [ ]

- name: S/blocked
  color: '97988B'
  description: 'Status: Blocked by something else'
  aliases: [ ]

- name: S/pending-release
  color: '0E8A16'
  description: 'Status: Finished, pending release'
  aliases: [ fixed,complete,finished ]

- name: S/in-progress
  color: '36210B'
  description: 'Status: Being worked on'
  aliases: [ ]

- name: S/info-needed
  color: '4A4800'
  description: 'Status: Awaiting further information'
  aliases: [ ]

- name: S/needs-triage
  color: 'D4C31A'
  description: 'Status: Needs triage'
  aliases: [ ]


- name: T/addition
  color: '139399'
  description: 'Type: New feature'
  aliases: [ ]

- name: T/bug
  color: 'A83400'
  description: 'Type: Bug'
  aliases: [ ]

- name: T/compat
  color: '490839'
  description: 'Type: Compatibility'
  aliases: [ ]

- name: T/enhancement
  color: '0052CC'
  description: 'Type: Enhancement or optimization'
  aliases: [ ]

- name: T/fix
  color: '0E8A16'
  description: 'Type: Bugfix'
  aliases: [ ]

- name: T/port
  color: '5319E7'
  description: 'Type: Upgrade or downgrade game version'
  aliases: [ ]

- name: T/security
  color: 'B60205'
  description: 'Type: Security'
  aliases: [ ]

- name: T/translation
  color: '8C02DA'
  description: 'Type: Translation'
  aliases: [ ]
